# Generated by Django 2.2.5 on 2019-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donator',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
