# Generated by Django 2.2.5 on 2019-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonation', '0002_auto_20190905_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
