# Generated by Django 2.2.5 on 2019-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonation', '0003_donator_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30),
        ),
    ]
